In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

import joblib

In [ ]:

import pandas as pd
import numpy as np


import matplotlib.pyplot as plt
import seaborn as sns


import warnings
warnings.filterwarnings("ignore")


from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)


from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [3]:
df = pd.read_csv("../data/project/house_prices.csv")

In [4]:
df.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

In [5]:
df.info

<bound method DataFrame.info of          Index                                              Title  \
0            0  1 BHK Ready to Occupy Flat for sale in Srushti...
1            1  2 BHK Ready to Occupy Flat for sale in Dosti V...
2            2  2 BHK Ready to Occupy Flat for sale in Sunrise...
3            3        1 BHK Ready to Occupy Flat for sale Kasheli
4            4  2 BHK Ready to Occupy Flat for sale in TenX Ha...
...        ...                                                ...
187526  187526  3 BHK Ready to Occupy Flat for sale in Bollywo...
187527  187527  3 BHK Ready to Occupy Flat for sale in Sushma ...
187528  187528  3 BHK Ready to Occupy Flat for sale in Bollywo...
187529  187529  2 BHK Ready to Occupy Flat for sale in Friends...
187530  187530  3 BHK Ready to Occupy Flat for sale in Affinit...

                                              Description Amount(in rupees)  \
0       Bhiwandi, Thane has an attractive 1 BHK Flat f...           42 Lac
1       One can find this stunning 2 BHK flat for sale...           98 Lac
2       Up for immediate sale is a 2 BHK apartment in ...          1.40 Cr
3       This beautiful 1 BHK Flat is available for sal...           25 Lac
4       This lovely 2 BHK Flat in Pokhran Road, Thane ...          1.60 Cr
...                                                   ...               ...
187526  This magnificent 3 BHK Flat is available for s...           63 Lac
187527  Have a look at this immaculate 3 BHK flat for ...           55 Lac
187528  Gazipur, Zirakpur has an appealing 3 BHK flat ...           76 Lac
187529  Up for immediate sale is a 2 BHK apartment in ...           30 Lac
187530  This exquisite 3 BHK Flat is offered for sale ...          1.18 Cr

        Price (in rupees)  location Carpet Area         Status         Floor  \
0                  6000.0     thane    500 sqft  Ready to Move  10 out of 11
1                 13799.0     thane    473 sqft  Ready to Move   3 out of 22
2                 17500.0     thane    779 sqft  Ready to Move  10 out of 29
3                     NaN     thane    530 sqft  Ready to Move    1 out of 3
4                 18824.0     thane    635 sqft  Ready to Move  20 out of 42
...                   ...       ...         ...            ...           ...
187526             3225.0  zirakpur         NaN  Ready to Move    2 out of 4
187527             3274.0  zirakpur         NaN  Ready to Move    4 out of 6
187528             4343.0  zirakpur   1250 sqft  Ready to Move    1 out of 3
187529             4231.0  zirakpur         NaN  Ready to Move    2 out of 2
187530             6162.0  zirakpur         NaN  Ready to Move   5 out of 13

         Transaction  ...        facing             overlooking  \
0             Resale  ...           NaN                     NaN
1             Resale  ...          East             Garden/Park
2             Resale  ...          East             Garden/Park
3             Resale  ...           NaN                     NaN
4             Resale  ...          West  Garden/Park, Main Road
...              ...  ...           ...                     ...
187526  New Property  ...          East             Garden/Park
187527        Resale  ...  North - East  Garden/Park, Main Road
187528        Resale  ...          East  Garden/Park, Main Road
187529        Resale  ...           NaN               Main Road
187530        Resale  ...  North - East       Garden/Park, Pool

                                    Society Bathroom Balcony Car Parking  \
0       Srushti Siddhi Mangal Murti Complex        1       2         NaN
1                               Dosti Vihar        2     NaN      1 Open
2                      Sunrise by Kalpataru        2     NaN   1 Covered
3                                       NaN        1       1         NaN
4               TenX Habitat Raymond Realty        2     NaN   1 Covered
...                                     ...      ...     ...         ...
187526                    Bollywood Esencia        3       3   1 Covered
187527                   Sushma Urban Views        3     NaN   1 Covered
187528                    Bollywood Esencia        3       2  1 Covered,
187529                      Friends Enclave        2     NaN         NaN
187530                      Affinity Greens        4       4   1 Covered

                   Ownership Super Area Dimensions  Plot Area
0                        NaN        NaN        NaN        NaN
1                   Freehold        NaN        NaN        NaN
2                   Freehold        NaN        NaN        NaN
3                        NaN        NaN        NaN        NaN
4       Co-operative Society        NaN        NaN        NaN
...                      ...        ...        ...        ...
187526              Freehold  1953 sqft        NaN        NaN
187527                   NaN  1680 sqft        NaN        NaN
187528              Freehold        NaN        NaN        NaN
187529                   NaN   709 sqft        NaN        NaN
187530              Freehold  1915 sqft        NaN        NaN

[187531 rows x 21 columns]>

In [6]:
df.head

<bound method NDFrame.head of          Index                                              Title  \
0            0  1 BHK Ready to Occupy Flat for sale in Srushti...
1            1  2 BHK Ready to Occupy Flat for sale in Dosti V...
2            2  2 BHK Ready to Occupy Flat for sale in Sunrise...
3            3        1 BHK Ready to Occupy Flat for sale Kasheli
4            4  2 BHK Ready to Occupy Flat for sale in TenX Ha...
...        ...                                                ...
187526  187526  3 BHK Ready to Occupy Flat for sale in Bollywo...
187527  187527  3 BHK Ready to Occupy Flat for sale in Sushma ...
187528  187528  3 BHK Ready to Occupy Flat for sale in Bollywo...
187529  187529  2 BHK Ready to Occupy Flat for sale in Friends...
187530  187530  3 BHK Ready to Occupy Flat for sale in Affinit...

                                              Description Amount(in rupees)  \
0       Bhiwandi, Thane has an attractive 1 BHK Flat f...           42 Lac
1       One can find this stunning 2 BHK flat for sale...           98 Lac
2       Up for immediate sale is a 2 BHK apartment in ...          1.40 Cr
3       This beautiful 1 BHK Flat is available for sal...           25 Lac
4       This lovely 2 BHK Flat in Pokhran Road, Thane ...          1.60 Cr
...                                                   ...               ...
187526  This magnificent 3 BHK Flat is available for s...           63 Lac
187527  Have a look at this immaculate 3 BHK flat for ...           55 Lac
187528  Gazipur, Zirakpur has an appealing 3 BHK flat ...           76 Lac
187529  Up for immediate sale is a 2 BHK apartment in ...           30 Lac
187530  This exquisite 3 BHK Flat is offered for sale ...          1.18 Cr

        Price (in rupees)  location Carpet Area         Status         Floor  \
0                  6000.0     thane    500 sqft  Ready to Move  10 out of 11
1                 13799.0     thane    473 sqft  Ready to Move   3 out of 22
2                 17500.0     thane    779 sqft  Ready to Move  10 out of 29
3                     NaN     thane    530 sqft  Ready to Move    1 out of 3
4                 18824.0     thane    635 sqft  Ready to Move  20 out of 42
...                   ...       ...         ...            ...           ...
187526             3225.0  zirakpur         NaN  Ready to Move    2 out of 4
187527             3274.0  zirakpur         NaN  Ready to Move    4 out of 6
187528             4343.0  zirakpur   1250 sqft  Ready to Move    1 out of 3
187529             4231.0  zirakpur         NaN  Ready to Move    2 out of 2
187530             6162.0  zirakpur         NaN  Ready to Move   5 out of 13

         Transaction  ...        facing             overlooking  \
0             Resale  ...           NaN                     NaN
1             Resale  ...          East             Garden/Park
2             Resale  ...          East             Garden/Park
3             Resale  ...           NaN                     NaN
4             Resale  ...          West  Garden/Park, Main Road
...              ...  ...           ...                     ...
187526  New Property  ...          East             Garden/Park
187527        Resale  ...  North - East  Garden/Park, Main Road
187528        Resale  ...          East  Garden/Park, Main Road
187529        Resale  ...           NaN               Main Road
187530        Resale  ...  North - East       Garden/Park, Pool

                                    Society Bathroom Balcony Car Parking  \
0       Srushti Siddhi Mangal Murti Complex        1       2         NaN
1                               Dosti Vihar        2     NaN      1 Open
2                      Sunrise by Kalpataru        2     NaN   1 Covered
3                                       NaN        1       1         NaN
4               TenX Habitat Raymond Realty        2     NaN   1 Covered
...                                     ...      ...     ...         ...
187526                    Bollywood Esencia        3       3   1 Covered
187527                   Sushma Urban Views        3     NaN   1 Covered
187528                    Bollywood Esencia        3       2  1 Covered,
187529                      Friends Enclave        2     NaN         NaN
187530                      Affinity Greens        4       4   1 Covered

                   Ownership Super Area Dimensions  Plot Area
0                        NaN        NaN        NaN        NaN
1                   Freehold        NaN        NaN        NaN
2                   Freehold        NaN        NaN        NaN
3                        NaN        NaN        NaN        NaN
4       Co-operative Society        NaN        NaN        NaN
...                      ...        ...        ...        ...
187526              Freehold  1953 sqft        NaN        NaN
187527                   NaN  1680 sqft        NaN        NaN
187528              Freehold        NaN        NaN        NaN
187529                   NaN   709 sqft        NaN        NaN
187530              Freehold  1915 sqft        NaN        NaN

[187531 rows x 21 columns]>

In [7]:
import pandas as pd

df = pd.read_csv("../data/project/house_prices.csv")
df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [8]:
df.drop(
    columns=[
        "Title",
        "Description",
        "Society",
        "Dimensions",
        "Plot Area"
    ],
    inplace=True
)

In [9]:
df["Carpet Area"].head()

0    500 sqft
1    473 sqft
2    779 sqft
3    530 sqft
4    635 sqft
Name: Carpet Area, dtype: str

In [10]:
df["Carpet Area"] = (
    df["Carpet Area"]
    .str.replace(" sqft", "", regex=False)
)

df["Carpet Area"] = pd.to_numeric(
    df["Carpet Area"],
    errors="coerce"
)

In [11]:
df["Carpet Area"].head()

0    500.0
1    473.0
2    779.0
3    530.0
4    635.0
Name: Carpet Area, dtype: float64

In [12]:
df["Floor"].head()

0    10 out of 11
1     3 out of 22
2    10 out of 29
3      1 out of 3
4    20 out of 42
Name: Floor, dtype: str

In [13]:
df["Floor"] = df["Floor"].str.replace(
    "Ground",
    "0",
    regex=False
)

df["Floor"] = df["Floor"].str.extract(r"(\d+)")

df["Floor"] = pd.to_numeric(
    df["Floor"],
    errors="coerce"
)

In [14]:
df["Floor"].head()

0    10.0
1     3.0
2    10.0
3     1.0
4    20.0
Name: Floor, dtype: float64

In [15]:
df["Bathroom"].head()

0    1
1    2
2    2
3    1
4    2
Name: Bathroom, dtype: str

In [16]:
df["Bathroom"] = pd.to_numeric(
    df["Bathroom"],
    errors="coerce"
)

In [17]:
df["Bathroom"].head()

0    1.0
1    2.0
2    2.0
3    1.0
4    2.0
Name: Bathroom, dtype: float64

In [18]:
df["Car Parking"].head()

0          NaN
1       1 Open
2    1 Covered
3          NaN
4    1 Covered
Name: Car Parking, dtype: str

In [19]:
df["Car Parking"] = df["Car Parking"].str.extract(r"(\d+)")

df["Car Parking"] = pd.to_numeric(
    df["Car Parking"],
    errors="coerce"
)

In [20]:
df["Car Parking"].head()

0    NaN
1    1.0
2    1.0
3    NaN
4    1.0
Name: Car Parking, dtype: float64

In [21]:
df.head()

,Index,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Bathroom,Balcony,Car Parking,Ownership,Super Area
0,0,42 Lac,6000.0,thane,500.0,Ready to Move,10.0,Resale,Unfurnished,NaN,NaN,1.0,2,NaN,NaN,NaN
1,1,98 Lac,13799.0,thane,473.0,Ready to Move,3.0,Resale,Semi-Furnished,East,Garden/Park,2.0,NaN,1.0,Freehold,NaN
2,2,1.40 Cr,17500.0,thane,779.0,Ready to Move,10.0,Resale,Unfurnished,East,Garden/Park,2.0,NaN,1.0,Freehold,NaN
3,3,25 Lac,NaN,thane,530.0,Ready to Move,1.0,Resale,Unfurnished,NaN,NaN,1.0,1,NaN,NaN,NaN
4,4,1.60 Cr,18824.0,thane,635.0,Ready to Move,20.0,Resale,Unfurnished,West,"Garden/Park, Main Road",2.0,NaN,1.0,Co-operative Society,NaN

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Amount(in rupees)  187531 non-null  str
 2   Price (in rupees)  169866 non-null  float64
 3   location           187531 non-null  str
 4   Carpet Area        100428 non-null  float64
 5   Status             186916 non-null  str
 6   Floor              180453 non-null  float64
 7   Transaction        187448 non-null  str
 8   Furnishing         184634 non-null  str
 9   facing             117298 non-null  str
 10  overlooking        106095 non-null  str
 11  Bathroom           186668 non-null  float64
 12  Balcony            138596 non-null  str
 13  Car Parking        84174 non-null   float64
 14  Ownership          122014 non-null  str
 15  Super Area         79846 non-null   str
dtypes: float64(5), int64(1), str(10)
memory usage: 22.9 MB

In [23]:
df.describe()

,Index,Price (in rupees),Carpet Area,Floor,Bathroom,Car Parking
count,187531.000000,1.698660e+05,100428.000000,180453.000000,186668.000000,84174.000000
mean,93765.000000,7.583772e+03,1268.525909,4.459100,2.426640,4.036935
std,54135.681003,2.724171e+04,3129.311735,4.665197,0.863244,31.822614
min,0.000000,0.000000e+00,1.000000,0.000000,1.000000,1.000000
25%,46882.500000,4.297000e+03,801.000000,2.000000,2.000000,1.000000
50%,93765.000000,6.034000e+03,1071.000000,3.000000,2.000000,1.000000
75%,140647.500000,9.450000e+03,1500.000000,6.000000,3.000000,1.000000
max,187530.000000,6.700000e+06,709222.000000,200.000000,10.000000,999.000000

In [24]:
df.isnull().sum()

Index                     0
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           87103
Status                  615
Floor                  7078
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Bathroom                863
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
dtype: int64

In [25]:
import pandas as pd

df = pd.read_csv("../data/project/house_prices.csv")

print(df.head(10))
print()
print(df.info())
print()
print(df.shape)
print()
print(df.describe())

   Index                                              Title  \
0      0  1 BHK Ready to Occupy Flat for sale in Srushti...
1      1  2 BHK Ready to Occupy Flat for sale in Dosti V...
2      2  2 BHK Ready to Occupy Flat for sale in Sunrise...
3      3        1 BHK Ready to Occupy Flat for sale Kasheli
4      4  2 BHK Ready to Occupy Flat for sale in TenX Ha...
5      5  1 BHK Ready to Occupy Flat for sale in Virat A...
6      6         1 BHK Ready to Occupy Flat for sale Mumbra
7      7          1 BHK Ready to Occupy Flat for sale Kalwa
8      8          1 BHK Ready to Occupy Flat for sale Kalwa
9      9  3 BHK Ready to Occupy Flat for sale in Pride P...

                                         Description Amount(in rupees)  \
0  Bhiwandi, Thane has an attractive 1 BHK Flat f...           42 Lac
1  One can find this stunning 2 BHK flat for sale...           98 Lac
2  Up for immediate sale is a 2 BHK apartment in ...          1.40 Cr
3  This beautiful 1 BHK Flat is available for sal...           25 Lac
4  This lovely 2 BHK Flat in Pokhran Road, Thane ...          1.60 Cr
5  Creatively planned and constructed is a 1 BHK ...           45 Lac
6  This magnificent 1 BHK Flat is available for s...         16.5 Lac
7  Creatively planned and constructed is a 1 BHK ...           60 Lac
8  Discover this immaculate 1 BHK flat for sale a...           60 Lac
9  One can find this stunning 3 BHK flat for sale...          1.60 Cr

   Price (in rupees) location Carpet Area         Status            Floor  \
0             6000.0    thane    500 sqft  Ready to Move     10 out of 11
1            13799.0    thane    473 sqft  Ready to Move      3 out of 22
2            17500.0    thane    779 sqft  Ready to Move     10 out of 29
3                NaN    thane    530 sqft  Ready to Move       1 out of 3
4            18824.0    thane    635 sqft  Ready to Move     20 out of 42
5             6618.0    thane         NaN  Ready to Move       2 out of 7
6             2538.0    thane    550 sqft  Ready to Move       4 out of 5
7            10435.0    thane         NaN  Ready to Move  Ground out of 7
8            10000.0    thane         NaN  Ready to Move  Ground out of 2
9            11150.0    thane    900 sqft  Ready to Move      3 out of 27

  Transaction  ... facing             overlooking  \
0      Resale  ...    NaN                     NaN
1      Resale  ...   East             Garden/Park
2      Resale  ...   East             Garden/Park
3      Resale  ...    NaN                     NaN
4      Resale  ...   West  Garden/Park, Main Road
5      Resale  ...   East  Garden/Park, Main Road
6      Resale  ...    NaN                     NaN
7      Resale  ...    NaN                     NaN
8      Resale  ...    NaN                     NaN
9      Resale  ...   East             Garden/Park

                               Society Bathroom Balcony Car Parking  \
0  Srushti Siddhi Mangal Murti Complex        1       2         NaN
1                          Dosti Vihar        2     NaN      1 Open
2                 Sunrise by Kalpataru        2     NaN   1 Covered
3                                  NaN        1       1         NaN
4          TenX Habitat Raymond Realty        2     NaN   1 Covered
5                         Virat Aangan        1       1         NaN
6                                  NaN        1     NaN         NaN
7                                  NaN        1     NaN         NaN
8                                  NaN        1     NaN         NaN
9                          Pride Palms        3       1   1 Covered

              Ownership Super Area Dimensions  Plot Area
0                   NaN        NaN        NaN        NaN
1              Freehold        NaN        NaN        NaN
2              Freehold        NaN        NaN        NaN
3                   NaN        NaN        NaN        NaN
4  Co-operative Society        NaN        NaN        NaN
5  Co-operative Society   680 sqft        NaN        NaN
6                   NaN        NaN        NaN        NaN
7                   NaN   575 sqft        NaN        NaN
8  Co-operative Society   600 sqft        NaN        NaN
9              Freehold        NaN        NaN        NaN

[10 rows x 21 columns]

<class 'pandas.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  str
 2   Description        184508 non-null  str
 3   Amount(in rupees)  187531 non-null  str
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  str
 6   Carpet Area        106858 non-null  str
 7   Status             186916 non-null  str
 8   Floor              180454 non-null  str
 9   Transaction        187448 non-null  str
 10  Furnishing         184634 non-null  str
 11  facing             117298 non-null  str
 12  overlooking        106095 non-null  str
 13  Society            77853 non-null   str
 14  Bathroom           186703 non-null  str
 15  Balcony            138596 non-null  str
 16  Car Parking        84174 non-null   str
 17  Ownership          122014 non-null  str
 18  Super Area         79846 non-null   str
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), str(17)
memory usage: 30.0 MB
None

(187531, 21)

               Index  Price (in rupees)  Dimensions  Plot Area
count  187531.000000       1.698660e+05         0.0        0.0
mean    93765.000000       7.583772e+03         NaN        NaN
std     54135.681003       2.724171e+04         NaN        NaN
min         0.000000       0.000000e+00         NaN        NaN
25%     46882.500000       4.297000e+03         NaN        NaN
50%     93765.000000       6.034000e+03         NaN        NaN
75%    140647.500000       9.450000e+03         NaN        NaN
max    187530.000000       6.700000e+06         NaN        NaN

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  str
 2   Description        184508 non-null  str
 3   Amount(in rupees)  187531 non-null  str
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  str
 6   Carpet Area        106858 non-null  str
 7   Status             186916 non-null  str
 8   Floor              180454 non-null  str
 9   Transaction        187448 non-null  str
 10  Furnishing         184634 non-null  str
 11  facing             117298 non-null  str
 12  overlooking        106095 non-null  str
 13  Society            77853 non-null   str
 14  Bathroom           186703 non-null  str
 15  Balcony            138596 non-null  str
 16  Car Parking        84174 non-null   str
 17  Ownership          122014 non-null  str
 18  Super Area         79846 non-null   str
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), str(17)
memory usage: 30.0 MB

In [27]:
df.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.describe(include="all")

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
count,187531.000000,187531,184508,187531,1.698660e+05,187531,106858,186916,180454,187448,...,117298,106095,77853,186703,138596,84174,122014,79846,0.0,0.0
unique,NaN,32446,65634,1561,NaN,81,2758,1,947,4,...,8,19,10376,11,11,229,4,2976,NaN,NaN
top,NaN,2 BHK Ready to Occupy Flat for sale in Divyasr...,Multistorey apartment is available for sale. I...,Call for Price,NaN,new-delhi,1000 sqft,Ready to Move,2 out of 4,Resale,...,East,Main Road,Hamdam Apartment,2,2,1 Covered,Freehold,1100 sqft,NaN,NaN
freq,NaN,2106,2732,9684,NaN,27599,5285,186916,12433,144172,...,54741,32193,1648,93007,51809,38754,112229,2599,NaN,NaN
mean,93765.000000,NaN,NaN,NaN,7.583772e+03,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,54135.681003,NaN,NaN,NaN,2.724171e+04,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,46882.500000,NaN,NaN,NaN,4.297000e+03,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,93765.000000,NaN,NaN,NaN,6.034000e+03,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,140647.500000,NaN,NaN,NaN,9.450000e+03,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,187530.000000,NaN,NaN,NaN,6.700000e+06,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df.drop(columns=["Dimensions","Plot Area"], inplace=True)

In [31]:
df.drop(columns=["Title","Society"], inplace=True)

In [32]:
df.drop(columns=["Description"], inplace=True)

In [33]:
df["Carpet Area"] = (
    df["Carpet Area"]
    .str.replace(" sqft", "", regex=False)
)

df["Carpet Area"] = pd.to_numeric(
    df["Carpet Area"],
    errors="coerce"
)

In [34]:
df["Bathroom"] = pd.to_numeric(
    df["Bathroom"],
    errors="coerce"
)

In [35]:
df["Balcony"] = pd.to_numeric(
    df["Balcony"],
    errors="coerce"
)

In [36]:
df["Car Parking"] = df["Car Parking"].str.extract(r"(\d+)")

df["Car Parking"] = pd.to_numeric(
    df["Car Parking"],
    errors="coerce"
)

In [37]:
for col in df.columns:
    try:
        df[col].median()
    except:
        print(col)

Amount(in rupees)
location
Status
Floor
Transaction
Furnishing
facing
overlooking
Ownership
Super Area

In [38]:
text_cols = [
    "Amount(in rupees)",
    "location",
    "Status",
    "Floor",
    "Transaction",
    "Furnishing",
    "facing",
    "overlooking",
    "Ownership",
    "Super Area"
]

for col in text_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [39]:
for col in df.select_dtypes(include=["int64", "float64"]).columns:
    df[col] = df[col].fillna(df[col].median())

In [ ]:

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].fillna(df[col].mode()[0])


for col in df.select_dtypes(include=["int64", "float64"]).columns:
    df[col] = df[col].fillna(df[col].median())

In [41]:
X = df.drop("Amount(in rupees)", axis=1)
y = df["Amount(in rupees)"]


import joblib
from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in X.select_dtypes(include="object").columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))
    encoders[col] = le

joblib.dump(encoders, "label_encoder.pkl")

['label_encoder.pkl']

In [42]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].fillna(df[col].mode()[0])

for col in df.select_dtypes(include=["int64","float64"]).columns:
    df[col] = df[col].fillna(df[col].median())

In [43]:
from sklearn.preprocessing import LabelEncoder
import joblib

X = df.drop("Price (in rupees)", axis=1)
y = df["Price (in rupees)"]

encoders = {}

for col in X.select_dtypes(include="object").columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))
    encoders[col] = le

joblib.dump(encoders, "label_encoder.pkl")

['label_encoder.pkl']

In [44]:
df = df[df["Amount(in rupees)"] != "Call for Price"]

In [45]:
def convert_price(x):
    x = str(x).replace(",", "").strip()

    if "Cr" in x:
        return float(x.replace(" Cr", "")) * 10000000

    elif "Lac" in x:
        return float(x.replace(" Lac", "")) * 100000

    else:
        return float(x)


df["Amount(in rupees)"] = df["Amount(in rupees)"].apply(convert_price)

In [46]:
X = df.drop("Amount(in rupees)", axis=1)
y = df["Amount(in rupees)"]

In [47]:
from sklearn.preprocessing import LabelEncoder
import joblib

encoders = {}

for col in X.select_dtypes(include="object").columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))
    encoders[col] = le

joblib.dump(encoders, "label_encoder.pkl")

['label_encoder.pkl']

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [49]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [50]:
df.describe(include="all")

,Index,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Bathroom,Balcony,Car Parking,Ownership,Super Area
count,177847.000000,1.778470e+05,1.778470e+05,177847,177847.000000,177847,177847,177847,177847,177847,177847,177847.000000,177847.000000,177847.000000,177847,177847
unique,NaN,NaN,NaN,81,NaN,1,938,4,3,8,18,NaN,NaN,NaN,4,2897
top,NaN,NaN,NaN,new-delhi,NaN,Ready to Move,2 out of 4,Resale,Semi-Furnished,East,Main Road,NaN,NaN,NaN,Freehold,1100 sqft
freq,NaN,NaN,NaN,24945,NaN,177847,18386,135697,84935,117980,105508,NaN,NaN,NaN,168336,104179
mean,93337.800542,1.198134e+07,7.514225e+03,NaN,1188.577063,NaN,NaN,NaN,NaN,NaN,NaN,2.446103,2.008878,2.385241,NaN,NaN
std,54508.769489,3.943827e+07,2.662538e+04,NaN,2350.840305,NaN,NaN,NaN,NaN,NaN,NaN,0.850811,0.815570,21.510467,NaN,NaN
min,0.000000,1.000000e+05,0.000000e+00,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,NaN
25%,45674.500000,4.840000e+06,4.400000e+03,NaN,1029.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,1.000000,1.000000,NaN,NaN
50%,93404.000000,7.800000e+06,6.034000e+03,NaN,1071.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,1.000000,NaN,NaN
75%,141112.500000,1.450000e+07,8.999000e+03,NaN,1160.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,2.000000,1.000000,NaN,NaN
max,187530.000000,1.400300e+10,6.700000e+06,NaN,709222.000000,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,10.000000,999.000000,NaN,NaN

In [51]:
print(X_train.dtypes)

print("\nColumns with object:")
print(X_train.select_dtypes(include="object").columns)

Index                  int64
Price (in rupees)    float64
location               int64
Carpet Area          float64
Status                 int64
Floor                  int64
Transaction            int64
Furnishing             int64
facing                 int64
overlooking            int64
Bathroom             float64
Balcony              float64
Car Parking          float64
Ownership              int64
Super Area             int64
dtype: object

Columns with object:
Index([], dtype='str')

In [52]:
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [53]:
y_pred = model.predict(X_test)

In [54]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 886957.9955018273
MSE: 4016963814560095.0
R2 Score: 0.31208463076493986

In [55]:
print("MAE:", mean_absolute_error(y_test, y_pred))

MAE: 886957.9955018273

In [56]:
print(y_test.describe())

count    3.557000e+04
mean     1.237400e+07
std      7.641657e+07
min      1.000000e+05
25%      4.910000e+06
50%      7.800000e+06
75%      1.467500e+07
max      1.400300e+10
Name: Amount(in rupees), dtype: float64

In [57]:
print(y_test.min())
print(y_test.max())

100000.0
14003000000.0

In [58]:
df[df["Amount(in rupees)"] == 0].shape

(0, 16)

In [59]:
df.isnull().sum()

Index                0
Amount(in rupees)    0
Price (in rupees)    0
location             0
Carpet Area          0
Status               0
Floor                0
Transaction          0
Furnishing           0
facing               0
overlooking          0
Bathroom             0
Balcony              0
Car Parking          0
Ownership            0
Super Area           0
dtype: int64

In [60]:
df.head

<bound method NDFrame.head of          Index  Amount(in rupees)  Price (in rupees)  location  Carpet Area  \
0            0          4200000.0             6000.0     thane        500.0
1            1          9800000.0            13799.0     thane        473.0
2            2         14000000.0            17500.0     thane        779.0
3            3          2500000.0             6034.0     thane        530.0
4            4         16000000.0            18824.0     thane        635.0
...        ...                ...                ...       ...          ...
187526  187526          6300000.0             3225.0  zirakpur       1071.0
187527  187527          5500000.0             3274.0  zirakpur       1071.0
187528  187528          7600000.0             4343.0  zirakpur       1250.0
187529  187529          3000000.0             4231.0  zirakpur       1071.0
187530  187530         11800000.0             6162.0  zirakpur       1071.0

               Status         Floor   Transaction      Furnishing  \
0       Ready to Move  10 out of 11        Resale     Unfurnished
1       Ready to Move   3 out of 22        Resale  Semi-Furnished
2       Ready to Move  10 out of 29        Resale     Unfurnished
3       Ready to Move    1 out of 3        Resale     Unfurnished
4       Ready to Move  20 out of 42        Resale     Unfurnished
...               ...           ...           ...             ...
187526  Ready to Move    2 out of 4  New Property  Semi-Furnished
187527  Ready to Move    4 out of 6        Resale     Unfurnished
187528  Ready to Move    1 out of 3        Resale       Furnished
187529  Ready to Move    2 out of 2        Resale  Semi-Furnished
187530  Ready to Move   5 out of 13        Resale  Semi-Furnished

              facing             overlooking  Bathroom  Balcony  Car Parking  \
0               East               Main Road       1.0      2.0          1.0
1               East             Garden/Park       2.0      2.0          1.0
2               East             Garden/Park       2.0      2.0          1.0
3               East               Main Road       1.0      1.0          1.0
4               West  Garden/Park, Main Road       2.0      2.0          1.0
...              ...                     ...       ...      ...          ...
187526          East             Garden/Park       3.0      3.0          1.0
187527  North - East  Garden/Park, Main Road       3.0      2.0          1.0
187528          East  Garden/Park, Main Road       3.0      2.0          1.0
187529          East               Main Road       2.0      2.0          1.0
187530  North - East       Garden/Park, Pool       4.0      4.0          1.0

                   Ownership Super Area
0                   Freehold  1100 sqft
1                   Freehold  1100 sqft
2                   Freehold  1100 sqft
3                   Freehold  1100 sqft
4       Co-operative Society  1100 sqft
...                      ...        ...
187526              Freehold  1953 sqft
187527              Freehold  1680 sqft
187528              Freehold  1100 sqft
187529              Freehold   709 sqft
187530              Freehold  1915 sqft

[177847 rows x 16 columns]>

In [61]:
print(df[["location", "Carpet Area"]].info())

<class 'pandas.DataFrame'>
Index: 177847 entries, 0 to 187530
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   location     177847 non-null  str
 1   Carpet Area  177847 non-null  float64
dtypes: float64(1), str(1)
memory usage: 4.1 MB
None

In [62]:
df.describe(include="all")

,Index,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Bathroom,Balcony,Car Parking,Ownership,Super Area
count,177847.000000,1.778470e+05,1.778470e+05,177847,177847.000000,177847,177847,177847,177847,177847,177847,177847.000000,177847.000000,177847.000000,177847,177847
unique,NaN,NaN,NaN,81,NaN,1,938,4,3,8,18,NaN,NaN,NaN,4,2897
top,NaN,NaN,NaN,new-delhi,NaN,Ready to Move,2 out of 4,Resale,Semi-Furnished,East,Main Road,NaN,NaN,NaN,Freehold,1100 sqft
freq,NaN,NaN,NaN,24945,NaN,177847,18386,135697,84935,117980,105508,NaN,NaN,NaN,168336,104179
mean,93337.800542,1.198134e+07,7.514225e+03,NaN,1188.577063,NaN,NaN,NaN,NaN,NaN,NaN,2.446103,2.008878,2.385241,NaN,NaN
std,54508.769489,3.943827e+07,2.662538e+04,NaN,2350.840305,NaN,NaN,NaN,NaN,NaN,NaN,0.850811,0.815570,21.510467,NaN,NaN
min,0.000000,1.000000e+05,0.000000e+00,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,NaN
25%,45674.500000,4.840000e+06,4.400000e+03,NaN,1029.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,1.000000,1.000000,NaN,NaN
50%,93404.000000,7.800000e+06,6.034000e+03,NaN,1071.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,1.000000,NaN,NaN
75%,141112.500000,1.450000e+07,8.999000e+03,NaN,1160.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,2.000000,1.000000,NaN,NaN
max,187530.000000,1.400300e+10,6.700000e+06,NaN,709222.000000,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,10.000000,999.000000,NaN,NaN

In [63]:

df.info()

<class 'pandas.DataFrame'>
Index: 177847 entries, 0 to 187530
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              177847 non-null  int64
 1   Amount(in rupees)  177847 non-null  float64
 2   Price (in rupees)  177847 non-null  float64
 3   location           177847 non-null  str
 4   Carpet Area        177847 non-null  float64
 5   Status             177847 non-null  str
 6   Floor              177847 non-null  str
 7   Transaction        177847 non-null  str
 8   Furnishing         177847 non-null  str
 9   facing             177847 non-null  str
 10  overlooking        177847 non-null  str
 11  Bathroom           177847 non-null  float64
 12  Balcony            177847 non-null  float64
 13  Car Parking        177847 non-null  float64
 14  Ownership          177847 non-null  str
 15  Super Area         177847 non-null  str
dtypes: float64(6), int64(1), str(9)
memory usage: 23.1 MB

In [64]:
df.isnull().sum()

Index                0
Amount(in rupees)    0
Price (in rupees)    0
location             0
Carpet Area          0
Status               0
Floor                0
Transaction          0
Furnishing           0
facing               0
overlooking          0
Bathroom             0
Balcony              0
Car Parking          0
Ownership            0
Super Area           0
dtype: int64

In [65]:
df.columns

Index(['Index', 'Amount(in rupees)', 'Price (in rupees)', 'location',
       'Carpet Area', 'Status', 'Floor', 'Transaction', 'Furnishing', 'facing',
       'overlooking', 'Bathroom', 'Balcony', 'Car Parking', 'Ownership',
       'Super Area'],
      dtype='str')

In [66]:
df.duplicated().sum()

np.int64(0)

In [67]:
import joblib

joblib.dump(model, "house_price_model.pkl")

['house_price_model.pkl']

In [68]:
print(X.columns)

Index(['Index', 'Price (in rupees)', 'location', 'Carpet Area', 'Status',
       'Floor', 'Transaction', 'Furnishing', 'facing', 'overlooking',
       'Bathroom', 'Balcony', 'Car Parking', 'Ownership', 'Super Area'],
      dtype='str')

In [69]:
print(X.columns)

Index(['Index', 'Price (in rupees)', 'location', 'Carpet Area', 'Status',
       'Floor', 'Transaction', 'Furnishing', 'facing', 'overlooking',
       'Bathroom', 'Balcony', 'Car Parking', 'Ownership', 'Super Area'],
      dtype='str')

In [70]:
print(df["location"].head())

0    thane
1    thane
2    thane
3    thane
4    thane
Name: location, dtype: str

In [71]:
print(df["location"].unique()[:50])

<StringArray>
[        'thane',   'navi-mumbai',        'nagpur',        'mumbai',
     'ahmedabad',     'bangalore',       'chennai',       'gurgaon',
     'hyderabad',        'indore',        'jaipur',       'kolkata',
       'lucknow',     'new-delhi',         'noida',          'pune',
          'agra',    'ahmadnagar',     'allahabad',    'aurangabad',
      'badlapur',       'belgaum',       'bhiwadi',      'bhiwandi',
        'bhopal',   'bhubaneswar',    'chandigarh',    'coimbatore',
      'dehradun',      'durgapur',     'ernakulam',     'faridabad',
     'ghaziabad',           'goa', 'greater-noida',        'guntur',
      'guwahati',       'gwalior',      'haridwar',      'jabalpur',
    'jamshedpur',       'jodhpur',        'kalyan',        'kanpur',
         'kochi',     'kozhikode',      'ludhiana',       'madurai',
     'mangalore',        'mohali']
Length: 50, dtype: str

In [72]:
for col in encoders:
    print(col, encoders[col].classes_[:10])

location ['agra' 'ahmadnagar' 'ahmedabad' 'allahabad' 'aurangabad' 'badlapur'
 'bangalore' 'belgaum' 'bhiwadi' 'bhiwandi']
Status ['Ready to Move']
Floor ['1' '1 out of 1' '1 out of 10' '1 out of 11' '1 out of 12' '1 out of 13'
 '1 out of 14' '1 out of 15' '1 out of 150' '1 out of 16']
Transaction ['New Property' 'Other' 'Rent/Lease' 'Resale']
Furnishing ['Furnished' 'Semi-Furnished' 'Unfurnished']
facing ['East' 'North' 'North - East' 'North - West' 'South' 'South - East'
 'South -West' 'West']
overlooking ['Garden/Park' 'Garden/Park, Main Road' 'Garden/Park, Main Road, Pool'
 'Garden/Park, Not Available' 'Garden/Park, Pool'
 'Garden/Park, Pool, Main Road' 'Main Road' 'Main Road, Garden/Park'
 'Main Road, Garden/Park, Pool' 'Main Road, Not Available']
Ownership ['Co-operative Society' 'Freehold' 'Leasehold' 'Power Of Attorney']
Super Area ['1 sqft' '10,000 sqft' '10,019 sqft' '10,590 sqft' '100 sqft' '100 sqm'
 '100 sqyrd' '1000 sqft' '1000 sqyrd' '1001 sqft']

In [ ]:
import joblib


model = joblib.load("house_price_model.pkl")


joblib.dump(
    model,
    "house_price_model_compressed.pkl",
    compress=9
)

print("Done")

Done